name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show machine details
        run: |
          hostname
          whoami
          pwd
